MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doggy_daycare.urls')),

    # Include authentication-related URL patterns from 'django.contrib.auth'
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

MySite/doggy_daycare/urls.py
from django.urls import path, include
from . import views

# Define the app name
app_name = 'doggy_daycare'

urlpatterns = [
    # URL for the home page
    path('', views.home, name='home'),
    
    # URL  for displaying all bookings
    path('bookings/', views.all_bookings, name='bookings'),
    
    # URL for adding a new booking
    path('add_booking/', views.add_booking, name='add-booking'),
    
    # URL for updating a booking
    path('update_booking/<booking_id>', views.update_booking, name='update-booking'),
    
    # URL for deleting a booking
    path('delete_booking/<booking_id>', views.delete_booking, name='delete-booking'),
]

MySite/doggy_daycare/models.py
from django.db import models

# Create your models here.
class Booking(models.Model):
    first_name = models.CharField('Owner First Name', max_length=50)
    last_name = models.CharField('Owner Last Name', max_length=50)
    pet = models.CharField('Pet Name', max_length=120)
    date = models.DateTimeField('Booking date')
    number = models.CharField('Phone Number', max_length=15)
    email = models.EmailField('Email Address')
    description = models.TextField(blank=True)


    # Define a string representation for instances of the model
    def __str__(self):
        return self.first_name + ' ' + self.last_name + ', ' + self.pet

MySite/doggy_daycare/forms.py
from django import forms
from django.forms import ModelForm
from .models import Booking

# Define a form class
class BookingForm(ModelForm):
    class Meta:
        # Specify the model to which this form is related
        model = Booking
        
        # Define the fields to be included in the form
        fields = ('first_name', 'last_name', 'pet', 'date', 'number', 'email', 'description')
        
        # Customize the labels for form fields (empty strings here for no labels)
        labels = {
            'first_name': '',
            'last_name': '',
            'pet': '',
            'date': '',
            'number': '',
            'email': '',
            'description': '',
        }

        # Customize the widgets for form fields to specify attributes
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the owner\'s first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the owner\'s last name'}),
            'pet': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the name of the pet'}),
            'date': forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Enter the date of the booking (format: yyyy-mm-dd/00:00:00)'}),
            'number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the owner\'s phone number'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter the owner\'s email address'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter a short description of what to do for the pet'}),
        }

MySite/doggy_daycare/views.py
from django.shortcuts import render, redirect
from .models import Booking
from .forms import BookingForm
from django.http import HttpResponseRedirect

def home(request):
    """
    Render the home page.

    This view function renders the home page of the Doggy Daycare website.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The rendered home page.
    :rtype: HttpResponse
    """
    return render(request, 'doggy_daycare/home.html', {})

def all_bookings(request):
    """
    Display a list of all bookings.

    This view function retrieves all Booking objects from the database and orders them by date.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The rendered booking list page.
    :rtype: HttpResponse
    """
    # Query the database to retrieve all Booking objects and order them by date
    booking_list = Booking.objects.all().order_by('date')
    return render(request, 'doggy_daycare/booking_list.html', {
        'booking_list': booking_list,
    })

def add_booking(request):
    """
    Add a new booking.

    This view function allows users to submit a new booking using a form. If the form is valid, the booking is saved,
    and the user is redirected to a success page.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The rendered booking form or a success page upon successful submission.
    :rtype: HttpResponse
    """
    submitted = False
    if request.method == 'POST':
        # If the request method is POST, process the form data
        form = BookingForm(request.POST)
        if form.is_valid():
            # If the form is valid, save the booking and redirect to a success page
            form.save()
            return HttpResponseRedirect('/add_booking?submitted=True')
    else:
        # If the request method is not POST, display the booking form
        form = BookingForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'doggy_daycare/add_booking.html', {
        'form': form,
        'submitted': submitted,
    })

def update_booking(request, booking_id):
    """
    Update an existing booking.

    This view function allows users to update an existing booking. It retrieves the Booking object with the specified
    booking_id from the database and pre-fills a form with the existing data. If the form is valid, the updated booking
    is saved, and the user is redirected to the bookings list.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :param booking_id: The ID of the booking to be updated.
    :type booking_id: int
    :return: The rendered booking update form or a redirect to the booking list upon successful update.
    :rtype: HttpResponse
    """
    # Retrieve the Booking object with the specified booking_id from the database
    booking = Booking.objects.get(pk=booking_id)
    # Create a form with the booking data so that we can see what's already there to be updated
    form = BookingForm(request.POST or None, instance=booking)
    if form.is_valid():
        # If the form is valid, save the updated booking and redirect to the bookings list
        form.save()
        return redirect('/bookings/')

    return render(request, 'doggy_daycare/update_booking.html', {
        'booking': booking,
        'form': form,
    })

def delete_booking(request, booking_id):
    """
    Delete an existing booking.

    This view function allows users to delete an existing booking. It retrieves the Booking object with the specified
    booking_id from the database and deletes it. After deletion, the user is redirected to the bookings list.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :param booking_id: The ID of the booking to be deleted.
    :type booking_id: int
    :return: A redirect to the booking list after deletion.
    :rtype: HttpResponse
    """
    # Retrieve the Booking object with the specified booking_id from the database
    booking = Booking.objects.get(pk=booking_id)
    # Delete the booking
    booking.delete()
    # Redirect to the bookings list
    return redirect('/bookings/')

MySite/doggy_daycare/templates/doggy_daycare/add_booking.html
{% extends "doggy_daycare/base.html" %}

{% block content %}

{% if user.is_authenticated %}
    <!-- Display the booking form if the user is logged in -->
    <div class="shadow p-5 my-5 bg-body rounded">
        <center>
            <div class="row mb-3">
                <div class="col my-2">
                    <h2>Add Booking to Database</h2>
                </div>
            </div>
            {% if submitted %}
                <!-- Display a success message if a booking was successfully submitted -->
                Your Booking was submitted successfully!!
            {% else %}
                <!-- Display the booking form -->
                <form action="" method="POST">
                    {% csrf_token %}
                    
                    <!-- Render form fields as paragraphs -->
                    {{ form.as_p }}

                    <input type="submit" value="Submit" class="btn btn-secondary">
                </form>
            {% endif %}
        </center>
    </div>
{% else %}
    <!-- Display a message and a login link if the user is not logged in -->
    <center>
        <h1>You may only add a booking if you are logged in!</h1>
        <a href="{% url 'login' %}" class="btn text-light my-2" style="background-color: #002c3d;">Login Here</a>
    </center>
{% endif %}

{% endblock %}

MySite/doggy_daycare/templates/doggy_daycare/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include Bootstrap CSS via CDN-->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">

    <title>Woof/Meow</title>

    <!-- A few CSS styles -->
    <style>
        body {
            background: #f1f2ff;
        }

        ul {
            list-style-position: inside; /* Center the bullet points */
            padding-left: 0; /* Remove default left padding for lists */
        }
    </style>

</head>

<body>

    <!-- Include Bootstrap JavaScript via CDN -->
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous">
    </script>

    <!-- Include a nav bar -->
    {% include 'doggy_daycare/navbar.html' %}

    <!-- Container for page content with margin -->
    <div class="container my-5">
        <!-- Display messages -->
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <!-- Close button for the alerts -->
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}
    </div>

</body>

</html>

MySite/doggy_daycare/templates/doggy_daycare/booking_list.html
{% extends "doggy_daycare/base.html" %}

{% block content %}

{% if user.is_authenticated %}
  <h2 class="text-center mb-5">Current Bookings:</h2>
  <ul>
    {% for booking in booking_list %}
      <!-- Display booking details in a card -->
      <div class="card text-center">
          <div class="card-header">
              Owner: {{ booking.first_name }} {{ booking.last_name }}
          </div>
          <div class="card-body">
              <h5 class="card-title">Pet name: {{ booking.pet }}</h5>
              <p class="card-text">Description: {{ booking.description }}</p>
          </div>
          <div class="card-footer text-muted">
              Date: {{ booking.date }}
          </div>
      </div>

      <!-- Display update and delete buttons for managers or staff users -->
      {% if user.role == "Manager" or user.is_staff %}
          <center>
              <a class="btn btn-secondary my-1" href="{% url 'doggy_daycare:update-booking' booking.id %}" role="button">Update</a>
              <a class="btn btn-danger my-1" href="{% url 'doggy_daycare:delete-booking' booking.id %}" role="button">Delete</a>
          </center>
      {% endif %}

      <br><br>
    {% endfor %}
  </ul>
{% else %}
  <center>
      <h1>You may only view bookings if you are logged in!</h1>
      <a href="{% url 'login' %}" class="btn text-light my-2" style="background-color: #002c3d;">Login Here</a>
  </center>
{% endif %}
  
{% endblock %}

MySite/doggy_daycare/templates/doggy_daycare/home.html
{% extends "doggy_daycare/base.html" %}
{% load static %}

{% block content %}
<div class="shadow p-5 my-5 bg-body rounded">

    <center>
        <div class="row">
            <div class="col my-2">
                <h2 style="font-style: italic;">Hello! Welcome to Doggy Daycare's webpage. Here you can view all bookings currently registered.</h2>
            </div>
        </div>
    </center>
    

    <div class="row">
        <!-- Display an image on the left -->
        <div class="col-md-4 mt-5">
            <img src="{% static 'doggy_daycare/header_image.jpg' %}" class="card-img-top" alt="Insert Photo Here" style="border: 2px solid rgb(255, 255, 255);">
        </div>
        <!-- Display text on the right -->
        <div class="col-md-8 align-self-center text-center mt-5">
            <div class="shadow p-4 mb-5 bg-body rounded">
                <h1 style="font-style: italic;">Does your pet need a good spa day? We got you covered!</h1>
                <p class="mt-5">Doggy Daycare © Specializing in making your pet the happiest they can be for the last 20 years.</p>
                <muted><p style="font-style: italic;">Founded in 2003.</p></muted>
            </div>
        </div>
    </div>

    <center>
    <div class="row">
        <div class="col my-2">
            <!-- List of services offered -->
            <h2>Services we offer: </h2>
            <ul>
                <li>Grooming services, including baths, haircuts, and nail trims</li>
                <li>Massages and relaxation therapy for pets</li>
                <li>Specialized skin and coat treatments</li>
                <li>Teeth cleaning and dental care</li>
                <li>Customized pet styling and coloring</li>
                <li>Pet facials and spa treatments</li>
                <li>Pet-friendly swimming pools</li>
                <li>Organic and natural pet products for sale</li>
                <li>Pet daycare and boarding services</li>
                <li>Pet photography</li>
            </ul>
            
        </div>
    </div>
    </center>

    <center>
    <div class="row">
        <div class="col my-2">
            <h3 class="mb-4">Thank you for stopping by!</h3>
        </div>
    </div>
    </center>

    <center>
        <muted>
            <div>
                Sponsored by: TheVetNextDoor.org ©
            </div>
        </muted>
    </center>

</div>

{% endblock %}

MySite/doggy_daycare/templates/doggy_daycare/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'doggy_daycare:home' %}">Doggy Daycare</a>

        <!-- Toggle button for small screens -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Nav links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- Link to the 'Bookings' page -->
                    <a class="nav-link" href="{% url 'doggy_daycare:bookings' %}">Bookings</a>
                </li>
                
                <!-- Display 'Add A Booking' link for Manager or staff users -->
                {% if user.role == "Manager" or user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'doggy_daycare:add-booking' %}">Add A Booking</a>
                    </li>
                {% endif %}
                
                <!-- Display 'Logout' or 'Login' link based on user login status -->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

MySite/doggy_daycare/templates/doggy_daycare/update_booking.html
{% extends "doggy_daycare/base.html" %}

{% block content %}
<div class="shadow p-5 my-5 bg-body rounded">

    <center>
    <div class="row">
        <div class="col my-2">
            <h2>Update Booking:</h2>
        </div>
    </div>
    <!-- Booking update form -->
    <form action="" method=POST>
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Update" class="btn btn-secondary">
    </form>
    </center>

{% endblock %}